### ISSUE TITLE
cvRef duplicates information in accession; remove cvRef or remove the prefix from accession

### ISSUE THREAD

**Issue by Ozzard** [HUPO-PSI/mzQC#100]
(See also #99; I recommend removing cvRef)

At present, cvRef is irrelevant to a consumer of mzQC.  The information present in that field is duplicated in accession, as accession always has the CV reference as a prefix.  The duplication leads to a potential loss of integrity if cvRef and accession contain different prefixes; this is undesirable for a communication standard and should be fixed.

I can see four options here:

* Do nothing.  Require the duplication.
* Deprecate the cvRef field, advising consumers not to rely on its presence, and slowly change producers to not write it.
* Remove the cvRef field pre-1.0, removing the duplication and possible integrity issues.
* Remove the prefix from accession, also removing the duplication and possible integrity issues.  This changes the syntax and semantics of accession, and is a breaking change for all mzQC writers and readers.

**Comment by mwalzer** [comment]
afaik, the accession bit is not necessarily duplicating cvref, there are ontologies that do not employ such a 'prefix'.
Also, although this is arcane, if you'd want to use an ontology (with the prefixes) in two different versions, how would you know from which version PREFIX:0123 came?

**Comment by mwalzer** [comment]
Of course I also cringe on that sort of duplication and pseudo namespacing in obo files, but I filed it as one of the many legacy issues we have to live with when building ontop of 'grown' structures (like psi-ms-cv).

**Comment by Ozzard** [comment]
Ah, OK - that makes sense; the pseudo-namespacing confused me.  Closing, though therefore see also a comment in #99 as I think we can agree that any controlled vocabulary can use any term ID and can duplicate other ontologies' term IDs.
