### ISSUE TITLE
Make sure important changes from other PRs are kept after merge of #102

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#108]
Make sure important changes from other PRs are kept after merge of #102.
Such as `is_obsolete` for corresponding lists or removal of [xrefs](https://github.com/HUPO-PSI/mzQC/blob/1c5dbe28a1caa943ebdd148f4060532fe2de0055/cv/qc-cv.obo#L81)

**Comment by bittremieux** [comment]
#102 has been merged a few months ago, so I presume this has been taken care of.
