### ISSUE TITLE
example renaming

### ISSUE THREAD

**Issue by cbielow** [HUPO-PSI/mzQC#111]
We should discuss the current naming scheme for the examples in `./doc/`:
`single-run.mzQC` describes a single run, but essentially its about 'runQualities'. So its easy to store multiple, but independent runs.

However, the name of `multi-run.mzQC` suggests that it explains how to store multiple runs, but in fact it explains `setQualities`.

I'd suggest to use different names:
`individual-runs.mzQC` and `set-of-runs.mzQC`
Other suggestions welcome :)
I know this somewhat breaks the links in the mzQC spec doc, but it should not be hard to adapt those before release 1.0.0, right?

**Comment by mwalzer** [comment]
Do you want to add this to #112 ?

**Comment by cbielow** [comment]
jep. can do
