### ISSUE TITLE
Improved browsing of qc-cv.obo

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzQC#119]
Related to #107, I suggest to have a better browsing of `qc-cv`, 
which would also help #115 . I vaguely recall that the OpenMS team 
had some tools in OpenMS to create static HTML from OBO files. 
Resulting HTML could be hosted on github pages then.
Yours, Steffen

**Comment by nilshoffmann** [comment]
Please see #122

**Comment by nilshoffmann** [comment]
Documentation is now in my repositories CI, deployed to https://nilshoffmann.github.io/obo-adoc/qc-cv.adoc.html

**Comment by sneumann** [comment]
The formatting looks good, but is lacking the navigationability. 
I found what I remembered:
http://htmlpreview.github.io/?https://github.com/nmrML/nmrML/blob/master/docs/mapping_and_cv.html
which is created by the OpenMS CVinspector in https://github.com/nmrML/nmrML/blob/master/Makefile#L127, unfortunately it requires a mapping file to work. A dummy mapping that allows the root term would work for the output. Yours, Steffen

**Comment by nilshoffmann** [comment]
@sneumann @mwalzer 

So, should we keep 
1. The generated html for the complete CV using my script
2. The generated *mapped* html for the CV using the mapping file using the OpenMS tools?

Or should we just use the OpenMS tool for both?

**Comment by bittremieux** [comment]
This might also be a relevant tool: http://vowl.visualdataweb.org/webvowl.html

We'd need to convert the OBO to OWL format, but those are mostly interchangeable. And the resulting interactive view looks pretty decent.

Ideally we should set something up with GitHub Actions to automatically generate an interactive webpage on all CV updates.

**Comment by mwalzer** [comment]
would #122 also work after #141? PSI-MS-CV might appreciate a browse-friendly CV, too

**Comment by nilshoffmann** [comment]
PSI-MS obo was one of my first use-cases for this, so yes, it should work. You just need to replace (or add) a line with the url for the psi-ms obo file. Here is a version from some time ago: https://nilshoffmann.github.io/obo-adoc/psi-ms.adoc.html

**Comment by bittremieux** [comment]
As we are merging into PSI-MS-CV, it will be possible to easily navigate the QC terms in their own branch using OLS (and other tools that already index the PSI-MS-CV).
