### ISSUE TITLE
Add more intermediate level classification of metrics

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzQC#120]
Related to #115, I would like to see a somewhat deeper nesting of metrics,
e.g. a category on PPM (or mass error) based ones. Or I might not 
have found them in the OBO. Yours, Steffen

**Comment by bittremieux** [comment]
We have now extended and harmonized the QC terms categorization for the first batch of terms that are going to be merged into the PSI-MS-CV (#165). Future term merging will be categorized similarly.
