### ISSUE TITLE
[CV request] Retention time mean shift

### ISSUE THREAD

**Issue by axelwalter** [HUPO-PSI/mzQC#121]
Name: Retention time mean shift

Definition: Based on expected and measured retention times of detected features the mean shift is calculated in seconds.

How to interpret the metric value: Low deviation in retention time indicates consistency and reproducibility in chromatographic separation.

Proposed value type:
- [x] single value
- [ ] n-tuple
- [ ] corresponding lists
- [ ] table
- [ ] matrix

Identifications needed (if appropriate):
- [x] ID based
- [ ] ID free
---
Name: Pump pressure mean

Definition: The mean pump pressure in bar.

How to interpret the metric value: Detecting inconsistencies in pump pressure between runs early helps troubleshooting and prevents instrument damage.

Proposed value type:
- [x] single value
- [ ] n-tuple
- [ ] corresponding lists
- [ ] table
- [ ] matrix

Identifications needed (if appropriate):
- [ ] ID based
- [x] ID free

**Comment by julianu** [comment]
Hej @axelwalter,

Apologies for the delay. Could you have a look at #125 for the new terms?

I assumed that the "Retention time mean shift" is a "multiple runs" metric.
And also, that the "Pump pressure mean" is a "single run" metric, calculating the mean of only one run.
Are these assumptions correct?

**Comment by axelwalter** [comment]
Yes "Pump pressure mean" is a single run metric. The idea behind "Retention time mean shift" is to identify variations in RT in a single run, based on expected/known and measured RTs. It can be calculated for example from a featureXML file with identified compounds. With a defined set of standards from which you know the RT in a healthy column you can detect any deviations early.

So both these terms are basically there to track and detect system and/or column health.

**Comment by julianu** [comment]
Ok, understood, so I changed the "Retention time mean shift" to a "single run" metric.
I also slightly changed the definition to "Based on reference retention times of detected features the mean shift of all features is calculated in seconds."

Is this ok?

**Comment by axelwalter** [comment]
that works, thanks!

**Comment by julianu** [comment]
The new terms were merged into the CV.
