### ISSUE TITLE
logo is text only

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#123]
While we at least have a [logo draft](doc/logo/mzQC.svg) (see also #16), I (generally) find text-only logos a bit wanting. I know it's not an easy task to come up with a general use logo, esp. for a bunch of scientists (read: _not_ graphics designers).

**Comment by mwalzer** [comment]
Maybe a rubber-stamp imprint styled logo?

**Comment by mwalzer** [comment]
Or a badge/award styled logo?

**Comment by bittremieux** [comment]
Logo should be fine for now, I don't think we need to keep this issue open indefinitely because, as mentioned, none of us is a graphical designer. Feel free to come up with new logo suggestions at any point.
