### ISSUE TITLE
PSI website

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#127]
Update [our page on the PSI website](https://psidev.info/groups/quality-control):

- [x] We need to remove mentions of qcML and should bring the goals and milestones in line with our current plans.
- [x] We can add an acknowledgments section with the names of people who have contributed in the past.

**Comment by mwalzer** [comment]
Lets have a collection for the ackn. list next call

**Comment by mwalzer** [comment]
I uncluttered the psidev.info website and structured it so that it can work as 
a) a primary destination for official documents
b) a secondary landing page (with the necessary orientation information and links)

**Comment by bittremieux** [comment]
Nice, I like this condensed version. Maybe you can still remove some outdated roles (secretary, MIAPE coordinator, editor) from the group structure?
