### ISSUE TITLE
[CV request] We need a cv param for mzQC as a file (just like MS:1000584)

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#130]
**Purpose:** The term is to be used to specify the file type of mzQC. E.g. as tag for source/input files, also in other formats as mzML.

**Name:** mzQC format

**Definition:** Proteomics Standards Initiative mzQC format for quality control data. `is_a: MS:1001459 ! file format`

**Comment:** None

**Value type:** N/A

**Unit:** N/A

**Category:** Structural term.

**Comment by julianu** [comment]
I would advocate to rather put this into the PSI-MS-CV, together with the "software generating QC metrics", which are still a stub at the very beginning of our current obo.
The reasoning for this is, that the file format should also be known by a consuming software, which only reads the PSI-MS-CV and might not be interested into QC.

**Comment by mwalzer** [comment]
or maybe `is_a: MS:1001040 ! intermediate analysis format` ?

**Comment by mwalzer** [comment]
see https://github.com/HUPO-PSI/psi-ms-CV/pull/71

**Comment by mwalzer** [comment]
Need it here #131

**Comment by bittremieux** [comment]
I think the request in the MS CV is better than having it as an intermediate format. 👍
