### ISSUE TITLE
Protein/Peptide identified numbers. How to detail method?

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#150]
https://github.com/HUPO-PSI/mzQC/blob/bf0eb4f6b7979ae714071c253d38be9e2db7fb61/cv/qc-cv.obo#L1308
https://github.com/HUPO-PSI/mzQC/blob/bf0eb4f6b7979ae714071c253d38be9e2db7fb61/cv/qc-cv.obo#L1327

How do we detail the protein inference/PSM (filter/FDR) method? Do we want this at all (or leave it to be looked up in the source file methods)?

**Comment by cbielow** [comment]
maybe we need an `aggregate` type - similar to `n-tuple`, but with predefined types of mixed type, e.g.
`[#peptides as int, #FDR method (as CV term) as string]`

**Comment by bittremieux** [comment]
My current preference would be to leave the details to the source file(s). There are just so many different steps that are relevant (which spectrum FDR? which peptide FDR? which protein FDR? where these different FDR levels combined? what was the FDR formula? was Percolator (or the like) post-processing used? etc.), that it's simply impossible to cover all possible situations.

I'd also _very strongly_ argue against introducing a new type just for a single metric. We shouldn't be introducing new data types at this point anymore.
If we really want both the number of peptides and the FDR threshold, for example, imo this works perfectly fine as two separate QC metrics right now.

**Comment by mwalzer** [comment]
> There are just so many different steps that are relevant ...

Indeed, too much. Maybe we could, at some point in the near future after release v1, write a guide/bp on how to document quality outside of (but in concert with) mzQC.
