### ISSUE TITLE
Do we need to detail the sequence encoding in the peptide sequence column?

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#155]
https://github.com/HUPO-PSI/mzQC/blob/bf0eb4f6b7979ae714071c253d38be9e2db7fb61/cv/qc-cv.obo#L651

**Comment by bittremieux** [comment]
I'd suggest defining the sequence as ProForma. That should cover pretty much all use cases.

**Comment by mwalzer** [comment]
Good, I like that. [This](https://github.com/HUPO-PSI/mzQC/commit/a24fdac22c37666ebadafd27740089a8cf82ee61) should do it? Is v2 finaliesed yet?

**Comment by bittremieux** [comment]
It's not fully finalized yet; the latest version is draft 14. The manuscript is currently under review at JPR and the specification should be finalized relatively soon. I think we can consider it stable at this point.
