### ISSUE TITLE
[CV request] DateTime of acquisition start/end

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#158]
**Purpose:** We have the run completion time on record in the runQuality metadata (via `fileProperties` + `MS:1000747 - completion time`), but for a number of metric calculations, it is advantageous to also have the start of the acquisition already, too. Also, the definition of `MS:1000747 - completion time` is not quite on spot: `def: "The time that a data processing action was finished." [PSI:MS]`.
```
[Term]
id: QC:4000277
name: DateTime of acquisition start
def: "The datetime string of the acquisition start timepoint in ISO8601 format" [PSI:QC]
comment: Acquisition start time as registered by the instrument.
is_a: QC:4000003 ! single value
is_a: QC:4000010 ! ID free
relationship: has_relation QC:4000013 ! QC metric relation: single run
```
and
```
[Term]
id: QC:4000278
name: DateTime of acquisition end
def: "The datetime string of the acquisition end timepoint in ISO8601 format" [PSI:QC]
comment: Acquisition end time as registered by the instrument.
is_a: QC:4000003 ! single value
is_a: QC:4000010 ! ID free
relationship: has_relation QC:4000013 ! QC metric relation: single run
```

Example value: "2012-01-30T07:30:51"

**Comment by mwalzer** [comment]
I suggest we use these two terms as the recommended fileProperties entries for MS runs as detailed in the spec doc.

**Comment by mwalzer** [comment]
Another thing to note: Our RT acquisition range also does not apply (and rightfully so!), because it details the earliest and latest time of scans.
```
id: QC:4000139
name: RT acquisition range
def: "Upper and lower limit of time at which spectra are recorded." [PSI:QC]
```

**Comment by bittremieux** [comment]
Why is the definition of [`MS:1000747`](https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L5229) ("completion time") insufficient? It is more general, but data acquisition seems to be a "data processing action" to me.

The counterpart of `MS:1000747` is [`MS:1002435`](https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L16635) ("data processing start time"). Again, a more general definition, but I think it works and we don't necessarily need to introduce new metrics.

`MS:1000016` ("scan start time") is definitely not applicable, because that's the time of a single scan (i.e. pretty much RT in LC-MS).

**Comment by mwalzer** [comment]
But how does a consumer software know it is ISO8601 encoded? Or anyone implementing it - will they look up a special section of the mzQC spec doc that defines all uses to be in ISO8601 (which doesn't exist yet, but I suppose we would need that)? 
And then there is the issue I have with the definition using time, sans the date part. Date is crucial for the set metric and monitoring purposes. 
And last, I dislike the use of 'data processing'. True though, it is data processing, but that is not the first thing that comes to mind, or the 2nd, or 10th, ...

**Comment by nilshoffmann** [comment]
The MS uses the xsdDateTime type, which is ISO8601 encoded: https://www.w3.org/TR/xmlschema-2/#dateTime

**Comment by bittremieux** [comment]
Consensus (?) from the teleconference: request child terms in the MS CV derived from MS:1000747 and MS:1002435 that explicitly specify that those are the _acquisition_ start and end times. Specify ISO8601 encoding using the `has_value_type` relationship.

**Comment by mwalzer** [comment]
https://github.com/HUPO-PSI/psi-ms-CV/issues/89
