### ISSUE TITLE
No read me, no wiki

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#18]

**Comment by mwalzer** [comment]
wiki is being built

**Comment by mwalzer** [comment]
We also need contribution guidelines. That's how it's called in GitHub anyway, we would need an easy to apply  guide for requesting new CV terms most.

**Comment by julianu** [comment]
We need to create a specification document.
Agreed to start a document in markdown in the folder "specification_document".

**Comment by mwalzer** [comment]
As a starting point, we could write down our decisions on the use of json values that have a resemblance to data frames and add the different types of values in metric, each with an example.

**Comment by mwalzer** [comment]
On the topic of a missing wiki, I think we should be careful not to disperse information to too many sources (readme wiki spec_doc readthedocs githubpages and so on) as we would have to keep all in sync and maintained. Closing this in favour of a clear set of specification documents and readme files in each repo folder.
