### ISSUE TITLE
mzML example still uses QC CV terms

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#185]
```
    QC:4000179 ! Charged spectra ratio +1 over +2
    QC:4000180 ! Charged spectra ratio +3 over +2
    QC:4000181 ! Charged spectra ratio +4 over +2
```

**Comment by mwalzer** [comment]
Opened an issue/term request with [PSI-MS](https://github.com/HUPO-PSI/psi-ms-CV/issues/118)

**Comment by bittremieux** [comment]
Where are these metrics used in the MTb example? I can't find it.

The MTb example uses QuaMeter metrics, which these aren't, so I'm a bit confused where they come in.

**Comment by mwalzer** [comment]
Apologies, you were spot on to be confused, the example was not mtb but [mzML](https://github.com/HUPO-PSI/mzQC/blob/bfe41836abbfef9333a631c57bbf85b42605a11c/doc/examples/mzml-mzqc-example.mzML#L328-L330).
