### ISSUE TITLE
Default values in analysisSoftware for version and uri

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzQC#199]
While trying to fix the validation I encountered validation errors on the analysisSoftware element. 
The schema and spec both require the `version` and `uri` attributes to be present. How do we treat cases, where no URI can be provided or no clear version is known / provided? Should we state explicit values to be reported? E.g. "NA" or "Unknown"? Should we use a valid URI, but one that indicates no link, something like https://hupo-psi.github.io/mzQC/unknown.html? Maybe adding an actual page that mentions that this refers to a software that has no URI?

Update: in [individual-runs.mzQC](https://github.com/HUPO-PSI/mzQC/blob/main/doc/examples/individual-runs.mzQC#L42), we apparently use `0` to indicate no version. (also in metabo-batches.mzQC, QC2-sample-example.mzQC)

If we decide on one way or another, we should also document such a use case in the spec doc.

Current state in the spec document:

<h3 class="western">analysisSoftware</h3>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
Software tool(s) used to generate the QC metrics.</p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
<br/>

</p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
Type: array</p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
Item types: extension of <font face="Consolas, serif"><font size="2" style="font-size: 11pt">cvParameter</font></font></p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
Min/max: (1, -)</p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
Object definition:</p>

Name | Type | Required | Description
-- | -- | -- | --
accession | string | true | Accession number identifying the term within its controlled 			vocabulary (pattern: ^[A-Z]+:[A-Z0-9]+$).
name | string | true | Name of the controlled vocabulary term describing the software 			tool.
description | string | false | Definition of the controlled vocabulary term.
value | any | false | Name of the software tool.
version | string | true | Version number of the software tool.
uri | string (URI) | true | Publicly accessible URI of the software tool or documentation.

<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
<br/>

</p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
Example:</p>
<p align="justify" style="line-height: 115%; orphans: 2; widows: 2; margin-bottom: 0cm">
<br/>

</p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
<font face="Consolas, serif"><font size="2" style="font-size: 11pt">&quot;analysisSoftware&quot;:
[</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
    <font face="Consolas, serif"><font size="2" style="font-size: 11pt">{</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
        <font face="Consolas, serif"><font size="2" style="font-size: 11pt">&quot;accession&quot;:
&quot;MS:1009002&quot;,</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
        <font face="Consolas, serif"><font size="2" style="font-size: 11pt">&quot;name&quot;:
&quot;QuaMeter IDFree&quot;,</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
        <font face="Consolas, serif"><font size="2" style="font-size: 11pt">&quot;version&quot;:
&quot;1.1.21070&quot;,</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
        <font face="Consolas, serif"><font size="2" style="font-size: 11pt">&quot;uri&quot;:
&quot;http://proteowizard.sourceforge.net/&quot;</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-left: 1.27cm; margin-bottom: 0cm">
<font face="Consolas, serif"><font size="2" style="font-size: 11pt">}</font></font></p>
<p align="justify" style="line-height: 100%; orphans: 2; widows: 2; margin-bottom: 0cm">
<font face="Consolas, serif"><font size="2" style="font-size: 11pt">]</font></font></p>

**Comment by bittremieux** [comment]
I think rather than updating the spec, those examples are invalid and should be updated. What are situations that no URI or version is available? For all software there should at least be a GitHub repository or associated paper I think, so that can be used as URI. For version, the actual version can be used, a git hash, or even a (publication) date.

**Comment by bittremieux** [comment]
Conclusion from teleconference:
- URI has been made optional.
- Clarification that alternative versions can be used.
