### ISSUE TITLE
availability in software packages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [HUPO-PSI/mzQC#2]
```
Provide documentation to QCML availability in various software packages.
(Bioconductor proteomics mass spec package?)

```

Original issue reported on code.google.com by `mathias....@gmail.com` on 5 Feb 2013 at 2:43

**Comment by bittremieux** [comment]
Implements listed [here](https://github.com/HUPO-PSI/mzQC/blob/master/software.md).
