### ISSUE TITLE
[CV] new CV column / attribute: type of MS experiment

### ISSUE THREAD

**Issue by eisenachM** [HUPO-PSI/mzQC#24]
In the current CV term collection (the separator-delimited file now suffixed '.md') it may also be interesting to report, for what MS experiment type (e.g. DDA-high-throughput MS/MS or SRM) a quality metric can only be useful (as Wout pointed out in the QC announcement manuscript, the total number of acquired MS/MS spectra is not so helpful for SRM). By adding such a column / attribute, it is not decided, whether this will be also included in a final CV collection / ontology or whether it is stated via text in a QC format specification document or whether it is modled by a rule in a semantic validator.

**Comment by mwalzer** [comment]
so you mean the [metric collection](https://github.com/HUPO-PSI/qcML-development/blob/master/cv/qc-metric-collection.md) ?

**Comment by mwalzer** [comment]
We might consider changing the collection overall ... see also: https://github.com/HUPO-PSI/qcML-development/pull/21#issuecomment-215409871

**Comment by julianu** [comment]
This will be handled by the tools, which actually write the metrics, and the metric descriptions.
