### ISSUE TITLE
ProteomeXchange interfacing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [HUPO-PSI/mzQC#3]
```
Investigate ability of PRIDE to handle QCML as part 
of ProteomeXchange submissions. 
Which would be feasible integrations?
```

Original issue reported on code.google.com by `mathias....@gmail.com` on 5 Feb 2013 at 2:48

**Comment by julianu** [comment]
For this issue, we could connect to the ELIXIR implementation study "Crowd-sourcing the annotation of public proteomics datasets to improve data reusability" (https://www.elixir-europe.org/about-us/implementation-studies/crowd-sourcing-proteomics).

**Comment by julianu** [comment]
PRIDE seems to be on the way to re-analyse submissions in the context of QC metrics. @ypriverol, are you planning to write out and store the metrics in mzQC, once we have a version 1.0?

**Comment by ypriverol** [comment]
WE have an ongoing project here for that. Keep in mind that we need first an stable released QCML file format if we want to go in that direction.

**Comment by bittremieux** [comment]
Punted for long-term mzQC development goals.
