### ISSUE TITLE
Refine qcML schema changes (0.0.8 to now ) avoiding ambiguities and bloat 

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#33]
This issue is to collect discussions and points of improvements for the current (0.0.8 to now) schema changes, some of which have already been identified in the monthly telcos by @bittremieux and @mwalzer.

**Comment by bittremieux** [comment]
No longer relevant after the switch to JSON -- which made the schema more streamlined incidentally.
