### ISSUE TITLE
Raw file information

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#34]
### What information should be stored about raw file(s) used to generate to QC data?

Currently the `RawFile` element supports the following attributes:

- A mandatory `id` and `name` attribute to identify the file. Should `name` be the original filename? Should it include the file extension or not? We should probably specify this in the documentation.
- A mandatory `location` attribute as a URI.
- An optional `methodFile_ref` reference to a methods file. The example given is a TraML file used for SRM analysis. When would this reference need to be used instead of only having an entry for the file in question as another external file?

And the following child elements:

- An optional `ExternalFormatDocumentation` with a URI pointing to additional documentation. As [remarked previously](https://gist.github.com/bittremieux/402c6ef08da1bba0a9495c2b0777eefc) it was unclear what this should contain and we decided to remove it (db7c7de).
- `FileFormat` as a `cvParam`. This imposes barely any restrictions in the XML schema, so probably external validation should happen to verify that a specific CV item denoting a file format is used here?
- Optional `userParam` and `cvParam` elements that can contain any other information.

What is the basis to put information as an attribute or an element? For example, both `location` and `ExternalFormatDocumentation` are simple URIs. There is of course a difference in importance between these 2 URIs, partially indicated by the mandatory/optional status.

### What information is still missing here?

- As identified in previous teleconferences (579a614, 2607c93), we should include a checksum to allow verification that the file hasn't changed.
- A `RawFile` can contain information about any type of input file. A flag should be included to specify what kind of file this is. (579a614)

### Other issues previously mentioned

- In November's teleconference it was mentioned that we need to be able to reference multiple raw files, for example for multiple files from different fractions. This is possible already as the maximum number of `RawFile` elements is unbounded.

**Comment by julianu** [comment]
The missing pieces are added by now, closed at PSI meeting.
