### ISSUE TITLE
Multiple values encoding

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#35]
Several ways have been suggested to encode a QC metric containing multiple values (i.e. quartiles, deciles, ...).

### Option 1: JSON list

```
<qualityParameter ID="METRIC003" cvRef="PSI-QC-CV" accession="C-8C" name="area under total ion current chromatogram quartiles Intensity Q1-Q3">
    <content cvRef="PSI-QC-CV" accession="list" value='3'>{'UO:0000189':[11235567,49344566,98047696]}</content>
</qualityParameter>
```

### Option 2: key-value pairs

```
<qualityParameter ID="METRIC002_1" cvRef="PSI-QC-CV" accession="C-8D" name="TIC quartile in relation to RT duration RT-TIC Q1-Q3">
    <content cvRef="PSI-QC-CV" accession="C-8D-json" value='4'>{Q1:0.27,Q2:0.4,Q3:0.74}</content>
</qualityParameter>
```

The previous consensus was the **JSON lists** are preferred.

As JSON is very flexible we should carefully specify what is and isn't allowed.

For example: how will we specify the number of elements in a list? Will the CV terms explicitly state "quartile" to indicate that 4 values are required or not? Previously we mentioned that the CV terms won't explicitly contain tags such as "Q1", "Q2", ... for quartiles etc., but that the number of quantiles will be derived from the number of values the metric takes. (0b134a6) In this case it will be crucial that this is stored consistently so that a correct interpretation is possible.

This is also important for file validation, which will need to be done externally.

**Comment by mwalzer** [comment]
So, it would be nice to have a definite description in the cv term definition, but still a somewhat self-explanatory and insta-parsable content in the cv term representation. My biggest concern here would be **units** because having them together with the values makes good for a lot of validation. Not all our values have a unit, but we still might want to enforce unit on every value and accept these cases where we have to put "no-unit" there and then

**Comment by mwalzer** [comment]
I think there are more than the two options if you consider term definition + units and current schema, then you could choose 
Sub element:
```
[Term]
id: QC:xxxxxxxx
name: Interval Acquisition range m/z
def: "TODO: description of this NIST metric group" [PSI:QC]
is_a: QC:3000016 ! QC metric
is_a: QC:xxxxxxxx ! tuple with unit 

[Schema]
<qualityParameter ID="METRIC001" cvRef="PSI-QC-CV" accession="QC:xxxxxxxx" name="Interval Acquisition range m/z"> 
    <content cvRef="PSI-QC-CV" accession="n - tuple" value='2'>{'MS:1000043':[400,1500]}</content>
</qualityParameter>
```	    
Explicit units:
```
[Term]
id: QC:xxxxxxxx
name: Interval Acquisition range m/z
def: "TODO: description of this NIST metric group" [PSI:QC]
is_a: QC:3000016 ! QC metric
is_a: QC:xxxxxxxx ! tuple 

[Schema]
<qualityParameter ID="METRIC001" cvRef="PSI-QC-CV" accession="QC:xxxxxxxx" name="Interval Acquisition range m/z" value="{'MS:1000043':[400,1500]}" /> 
```	    
Implicit 1:
```
[Term]
id: QC:xxxxxxxx
name: Interval Acquisition range m/z
def: "TODO: description of this NIST metric group" [PSI:QC]
is_a: QC:3000016 ! QC metric
is_a: QC:xxxxxxxx ! tuple with unit MS:1000043

[Schema]
<qualityParameter ID="METRIC001" cvRef="PSI-QC-CV" accession="QC:xxxxxxxx" name="Interval Acquisition range m/z" value="{[400,1500]}" /> 
```
	    
Implicit 2:
```
[Term]
id: QC:xxxxxxxx
name: Interval Acquisition range m/z
def: "TODO: description of this NIST metric group" [PSI:QC]
is_a: QC:3000016 ! QC metric
is_a: QC:xxxxxxxx ! unit MS:1000043

[Schema]
<qualityParameter ID="METRIC001" cvRef="PSI-QC-CV" accession="QC:xxxxxxxx" name="Interval Acquisition range m/z" value="{"1": 400, "2": 1500]}" /> 
```

**Comment by bittremieux** [comment]
I'd definitely prefer a list over key-value pairs, certainly if the keys are just indices as in the "Implicit 2" example.

Explicitly specifying the units seems like good practice to me. Most units in mass spec are standardized, so usually there shouldn't be any confusion, but still, sometimes people like to do things differently. Some people are just contrarian. 🙄 In that case explicitly specifying a unit could save us from a lot of trouble.

I'm not sure what the advantage of the sub element approach would be? This just adds extra complexity but wouldn't really make validation or other things easier as far as I can discern right now.

**Comment by bittremieux** [comment]
XML-JSON no longer relevant after change to full JSON. See #45 for the discussion on how to store multiple values in JSON.
