### ISSUE TITLE
Provenance

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#36]
The qcML file should specify the entire bioinformatics processing cycle up to generating the QC metrics.
As [remarked previously](https://gist.github.com/bittremieux/402c6ef08da1bba0a9495c2b0777eefc), this can be done through the general `cvParam` elements, but it might be useful to make this a bit more explicit and enforceable. At the very least we should carefully document this.

Additionally, information related to a contact person should be included. This has already been specified in the [MIAPE list](https://github.com/Jinmeng-QC/MIAPE-QC/blob/master/MIAPE_QC_draft.xlsx), so we should ensure that all MIAPE information can be found in the qcML file as well.

**Comment by julianu** [comment]
How to capture the provenance will be stated in the specification document.
