### ISSUE TITLE
Duplicate information

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#38]
As discussed in our recent teleconference (f52d365) we should compile a list of minimum information that is necessary for QC analyses, even though that information might already be stored in secondary files.

By duplicating that information into the qcML files directly this will facilitate (re)running QC analyses and simplify pipelines by not having to keep track of (all) prior files.

Current information that would be useful as identified during our teleconference is:

- Identification information: database, species, source (Uniprot), date.

Please discuss and specify further useful information.

**Comment by julianu** [comment]
This will be further explained in the specification documentation and MIAPE document.
