### ISSUE TITLE
metrics spanning multiple files

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#45]
Decide on the way to represent metrics spanning multiple files

related to #35

**Comment by mwalzer** [comment]
I put a gist here

**Comment by mwalzer** [comment]
Resolution after discussing on monthly call: go forward with snippet no.2

**Comment by bittremieux** [comment]
I didn't include this in my notes about last month's call, but what was the reason to pick option 2 over option 3? Shouldn't we prefer having the unit in there, just like for simple metrics in our examples? (Although the unit for those specific values in the gist probably shouldn't be fraction.)

**Comment by mwalzer** [comment]
For the sake of keeping it in line with the single file metrics, yes. I have a more detailed example for the call.
