### ISSUE TITLE
Intra-document references

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#50]
We need to keep element names document unique to be able to successfully reference items within a json document because we got rid of the 'id attribute'

**Comment by mwalzer** [comment]
see #47

**Comment by mwalzer** [comment]
This we have to specify in detail in the specification document.

**Comment by mwalzer** [comment]
Lets come up with some examples or if there are no good scrap internal referencing.

**Comment by julianu** [comment]
Advise people to do good (specified in specification document).
