### ISSUE TITLE
[CV] Chromatography related metric suggestions

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#52]
## Category: Chromatography
*	synonym: C-1A
	name: Fraction of repeat peptide IDs with	-4 min 
	def: 	Fraction of all peptides identified at least 4 min earlier than max MS1 for ID
	comment: Estimates very early peak broadening
*	synonym: C-1B
	name: Fraction of repeat peptide IDs with	+4 min
	def: 	Fraction of all peptides identified at least 4 min earlier than max MS1 for ID
	comment: Estimates very early peak broadening
*	synonym: C-2A
	name: Interquartile retention time period	Period (min)
	def: 	Time period over which 50% of peptides were identified
	comment: Longer times indicate better chromatographic separation
*	synonym: C-2B
	name: Interquartile retention time period	Pep ID rate
	def: 	Rate of peptide identification during C-2A
	comment: Higher rates indicate efficient sampling and identification
*	synonym: C-3A
	name: Peak width at half-height for IDs	Median value
	def: 	Median peak widths for all identified unique peptides (s)
	comment: Sharper peak widths indicate better chromatographic resolution
*	synonym: C-3B
	name: Interquartile distance of peak widths at half-height for IDs	
	def: 	Interquartile distance FWHM
	comment: Tighter distributions indicate more peak width uniformity	Measure of the distribution of the peak widths; small values indicate consistency
*	synonym: C-4A
	name: Peak widths at half-max over RT deciles for IDs	First decile
	def: 	Median peak width for identified peptides in first RT decile (early)
	comment: Estimates peak widths at the beginning of the gradient
*	synonym: C-4B
	name: Peak widths at half-max over RT deciles for IDs	Last decile
	def: 	Median peak width for identified peptides in first RT decile (end)
	comment: Estimates peak widths at the end of the gradient
*	synonym: C-4C
	name: Peak widths at half-max over RT deciles for IDs	Median decile
	def: 	Median peak width for identified peptides in first RT decile (middle)
	comment: Estimates peak widths at the middle of the gradient	
*	synonym: C-6A
	name: Peptide elution order trailing
	def: 	max diff in first N(a, b)/10 peptides; Fraction of extra early (hydrophilic) eluters; Peptide elution order can be used to measure elution differences early (hydrophilic) and late (hydrophobic) in the chromatographic gradient.
	comment: set metric for replicates
*	synonym: C-6B
	name: Peptide elution order tailing
	def: 	max diff in last N(a, b)/10 peptides; Fraction of extra late (hydrophobic) eluters		
	comment: set metric for replicates
*	synonym: C-7A
	name: Interval	Acquisition range RT
	def: 	What is the lowest and the highest sampled RT set to in the machine settings?
	comment: ?
*	synonym: C-7B
	name: Interval	RT-Duration
	def: 		What is the highest scan time observed minus the lowest scan time observed?
	comment: ?
*	synonym: C-8A
	name: total ion current chromatogram; Intensity collection
	def: 	the chromatogram in total
	* how to add comment of TIC is found in psi-ms.obo? MS:1000235
	comment: ?
*	synonym: C-8B
	name: area under total ion current chromatogram	Total intensity
	def: 	TIC AUC		
	comment: ?
*	synonym: C-8C
	name: area under total ion current chromatogram quartiles	Intensity Q1-Q4
	def: 	TIC AUC quartiles
	comment: ?
*	synonym: C-8D
	name: TIC quartile in relation to RT duration	RT-TIC Q1-Q4
	def: 	The interval when the first, .., last percentile of TIC accumulates divided by RT-Duration
	comment: ?
*	synonym: C-9
	name: pump pressure chromatogram
	def: 	list of pressure measurements ordered by RT
	is_a: UO:0000110 ! pascal
	comment: ?
*	Metric for number of drops in chromatograms (/histograms)
*	synonym: C-10A
	name: MS1-TIC-Change Q2-Q4 
	def: 	The log ratio for second, .., last percentile of TIC changes over first percentile of TIC changes ? log ratio
	comment: ?
*	synonym: C-10B
	name: MS1-TIC Q2-Q4
	def: 	The log ratio for second, .., last percentile of TIC over first percentile of TIC ? log ratio
	comment: ?

**Comment by julianu** [comment]
In #84 most of the proposed entries are added, please review the PR.

Additionally, here are some comments. On some terms I need some more explanation:
- C-1A and C-1B : one metric, containing corresponding lists, QC:4000069
- C-2A: QC:4000070
- C-2B: QC:4000071
- C-3A: QC:4000072
- C-3B: QC:4000073
- C-4A, C-4B, C-4C: one tuple of quantiles, QC:4000074
- C-6A: please explain a bit more, what is meant by this
- C-7A: please explain a bit more, what is meant by this
- C-7B: similar to QC:4000053
- C-8A: similar to QC:4000067
- C-8B: QC:4000075
- C-8C: QC:4000076
- C-8D: is this QC:4000054?
- C-9: QC:4000077
- C-10A: similar to QC:4000057
- C-10B: similar to QC:4000058

**Comment by mwalzer** [comment]
>  is this QC:4000054?
similar to QC:4000057
similar to QC:4000058

well spotted. I realized that quite some metrics don't have a readily accessible description. I'll try to improve that, but think that in the meantime we should go ahead with the PR.

**Comment by mwalzer** [comment]
C-6 is actually quite interesting, but only if you have a reference run. I'll try to improve the description:

N(a, b) are the peptides common in the run and the reference. N(a,b)_i..j are the first/latest eluting common peptides in the run, and C-6 is the maximum of ('elution rank' of peptide N(a,b)_i in run) - ('elution_rank' of peptide N(a,b)_i in reference) for i..j being the first/last tenth of common peptides. The elution rank difference gives you a measure of how many peptides are eluting early. The metric is finally normalised with dividing by the number of (identified) peptides in the run.

And 'C6-B' is trailing ; 'C6-A' is preceding - can you change the wording before adding them?

**Comment by julianu** [comment]
Ok, I tried to add the C-6 metrics to the PR, please check the descriptions:
C-6A: QC:4000078
C-6B: QC:4000079

C-7A: I still need an explanation for this

**Comment by julianu** [comment]
Bounce.

These terms are added, are they ok:
```
[Term]
id: QC:4000078
name: Peptide elution order trailing
def: "N(a, b) are the peptides common in the run and a reference run. N(a,b)_i to N(a,b)_j are the first to last eluting common peptides in the run ordered by retention time. This metric is the maximum of ('elution rank' of peptide N(a,b)_t in run) - ('elution_rank' of peptide N(a,b)_t in reference) for the first tenth of common peptides ordered by retention time. The metric is finally normalised with dividing by the number of (identified) peptides in the run." [PSI:QC]
comment: The elution rank difference gives you a measure of how many peptides are eluting early.
xref: value-type:xsd\:int "The allowed value-type for this CV term."
is_a: QC:4000003 ! single value
is_a: QC:4000009 ! ID based
is_a: QC:4000022 ! chromatogram metric
relationship: has_relation QC:4000014 ! QC metric relation: multiple runs

[Term]
id: QC:4000079
name: Peptide elution order preceding
def: "N(a, b) are the peptides common in the run and a reference run. N(a,b)_i to N(a,b)_j are the first to last eluting common peptides in the run ordered by retention time. This metric is the maximum of ('elution rank' of peptide N(a,b)_t in run) - ('elution_rank' of peptide N(a,b)_t in reference) for the last tenth of common peptides ordered by retention time. The metric is finally normalised with dividing by the number of (identified) peptides in the run." [PSI:QC]
comment: The elution rank difference gives you a measure of how many peptides are eluting late.
xref: value-type:xsd\:int "The allowed value-type for this CV term."
is_a: QC:4000003 ! single value
is_a: QC:4000009 ! ID based
is_a: QC:4000022 ! chromatogram metric
relationship: has_relation QC:4000014 ! QC metric relation: multiple runs
```

Could you give me a more fitting name, def and comment for:
```
synonym: C-7A
name: Interval Acquisition range RT
def: What is the lowest and the highest sampled RT set to in the machine settings?
comment: ?
```
