### ISSUE TITLE
[CV] PSI-MS relations to our entries (see #53)

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#54]
@dtabb73  added PSI-MS relations to the ID free metrics, e.g. `relationship: has_relation MS:1000041 ! charge state`.
[attached file from #53 ](https://github.com/HUPO-PSI/mzQC/files/2888627/20190122-qc-cv-with-metric-relationships-to-psi-ms.obo.txt)

**Comment by julianu** [comment]
Added in the next OBO
