### ISSUE TITLE
Sync examples and CV, spot in mzQC

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#56]
We still need to add many CV terms, keep our examples in-line, and have a way to spot offending entries in mzQC documents with a semantic validator. (Also, elaborate on what is 'offending'.)

**Comment by mwalzer** [comment]
See [QC:0000000](https://github.com/HUPO-PSI/mzQC/blob/e17587d7fb79064795dd05ead8ef64fb7b6dbecc/schema/v0_0_11/examples/20181005-1091_Pool_start_v0.2.qc.json#L166)

**Comment by bittremieux** [comment]
Such semantic validation is related to the first item in #51.

**Comment by bittremieux** [comment]
Make sure that we have examples with both Include nativeID and USI specifiers.

**Comment by bittremieux** [comment]
Include a small mzML-mzQC example file.

**Comment by bittremieux** [comment]
The updated continuous integration should take care of syntax issues. We will expand this with semantic validation for all example files when the mzqc-pylib is feature complete.
