### ISSUE TITLE
[CV] Issue with cv-term values and the use of cv in mzQC json

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#57]
e.g. in corresponding lists, defined: "lists with n elements each, n specified by the CV param value"
If cv value is n, then where do the lists go? This contradicts, how we use e.g. id: QC:4000050
name: XIC-WideFrac

**Comment by julianu** [comment]
Right, using the actual "cv-value" to  set the length of a tuple was my idea.
I was thinking about having a "cv-value" further describing the tuple and just have another "qc-metric-value" for the actual metric value. Whether the "cv-value" would be mandatory would be dependent on the actual CV, as would be the dimension (specifying a vector, matrix, table...).
Alternatively, the length could be given implicit by e.g. the vector length. But having it set explicitly adds another layer of control and correctness.

**Comment by bittremieux** [comment]
Yes, I was thinking about this while working on the semantic validation as well. If you have an `n-tuple` metric the semantic validation could potentially check whether all `n` values are present in the mzQC file, but right now the number of values isn't specified yet.

**Comment by julianu** [comment]
Decided in the PSI meeting:
We drop this redundant information and define the length of arrays/tables/matrices implicitly by the given json data.
