### ISSUE TITLE
[CV] CV term id prefixes

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#58]
The id prefix for the first three terms in the CV are `MS:` rather than `CV:`. Is this intentional @julianu? I guess there's no rule against that, but to be consistent it seems logical to prefix all ids with `QC:` instead.

**Comment by julianu** [comment]
The reason i prefixed them with MS is, that I thought they should definitely move into the psi-ms.obo in the end, while the actual metrics starting with QC might reside in a special qc-obo-file.
Alternatively, a point for discussion is: merging the complete OBO file into the psi-ms.obo
Currently, I would prefer to keep it split out, though.

**Comment by bittremieux** [comment]
All right, thanks for the explanation. So software should move to the MS CV? Or how do you make the distinction?

It's not really an issue, it just popped out to me while I was working on the semantic validation of mzQC files.

I agree that keeping the QC CV separate from the MS CV is preferable, at least at this stage.

**Comment by julianu** [comment]
Yes, the software should go there, like all search engines etc.

The intention was to try and keep only the things we need (i.e. metrics and their direct descriptions) in the QC obo.
