### ISSUE TITLE
[CV] define a way for users to request a new CV without a GitHub account

### ISSUE THREAD

**Issue by julianu** [HUPO-PSI/mzQC#59]
We should state an e- mail address or any other way how anybody could request a new CV parameter.

**Comment by julianu** [comment]
CVs can be requested by the mailing list.
Add some comment about this on the README

**Comment by julianu** [comment]
@mwalzer Let's build a template for the CV request when it goes through the creation of a new GitHub-issue.

**Comment by Ozzard** [comment]
As an alternative approach: allow users to use their own controlled vocabularies (as obo files), and add owl:sameAs to their own obo files if/when a standard term is created to map between the two terms in the different controlled vocabularies.

**Comment by julianu** [comment]
I created a template when using the GitHub-issues way to request new entries.
Not complete yet, but comments are welcome.

**Comment by bittremieux** [comment]
Looks pretty decent already. I didn't know you could have multiple issue templates, pretty cool. Would it be possible to make the "general issue" functionality a bit more prominent though? Right now it's just a simple text link, whereas the "request new CV issue" has a big green button. Although maybe this isn't possible?

Ideally users should provide as much details as possible in the CV issue, without providing a too steep barrier to entry of course. A tricky trade-off. :) New CV developments, such as #76 if incorporated for example, should be followed up by modifications to the issue template.

**Comment by cbielow** [comment]
what would be the mailing list's address?

**Comment by julianu** [comment]
For now, using "psidev-qc-dev [at] lists.sourceforge.net" would be the best, I guess.

**Comment by julianu** [comment]
I also added the template for "regular issue", so the default one is not so small.
With the changes introduced by @cbielow regarding the CV README, i will close this issue now.
