### ISSUE TITLE
Rename "cv" to "controlledVocabulary" in the JSON

### ISSUE THREAD

**Issue by Ozzard** [HUPO-PSI/mzQC#60]
The term "CV" is already well-known in the bioinformatics community as Coefficient of Variation, which is also a term associated with quality control.  I would strongly recommend not overloading the abbreviation, and I would strongly recommend not using abbreviations in a standard exchange format (we studiously avoided abbreviations when standardising OWL, for example).

May I request renaming the "cv" element in the JSON to "controloledVocabulary" to avoid this collision and consequent cognitive dissonance?

**Comment by julianu** [comment]
Very good remark, I think that should be easily possible and definitely improve readability.

**Comment by bittremieux** [comment]
Fixed in WIP pull request #70.
