### ISSUE TITLE
[Schema] Terminology: should mzQC use "Accession" or "Term" to describe something in a controlled vocabulary?

### ISSUE THREAD

**Issue by Ozzard** [HUPO-PSI/mzQC#61]
In the terminology world, unique elements in controlled vocabularies are generally referred to as terms.  The word "accession" is used in the bio and library community, generally for libraries and collections that change as the world being studied changes (new books are published, genes are identified, proteins are identified).

At present, mzQC uses "accession" in many places where, as a terminologist, I'd expect to see "term".  I'm raising this issue to flag that we may want a discussion around which term (sorry!) to adopt.

**Comment by bittremieux** [comment]
To be discussed during the teleconference.

I agree that "term" might make more sense, although historically the PSI formats have used "accession" to denote such references (see for example [mzML](https://github.com/HUPO-PSI/mzML/blob/e6612c379feeb89ad62ddd26c6b0864c33ee0aec/schema/mzML_dev.xsd#L169)).

**Comment by bittremieux** [comment]
We now properly use "term" to refer to CV terms in the specification document and elsewhere.
