### ISSUE TITLE
[Schema] cvParameter definition is referencing itself for a member definition (unit)

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#68]
Should we really do this? Maybe a cvTerm accession would do.
```
	"cvParameter": {
		"description": "Base element containing a reference to a controlled vocabulary.",
		"type": "object",
		"properties": {
			"cvRef": {
				"description": "Reference to the CV that contains the parameter definition.",
				"type": "string",
				"pattern": "^[A-Z]+$"
			},
			"accession": {
				"description": "Accession number identifying the parameter within its CV.",
				"type": "string",
				"pattern": "^[A-Z]+:[0-9]{7}$"
			},
			"name": {
				"description": "Name of the CV element describing the parameter.",
				"type": "string"
			},
			"description": {
				"description": "Description of the parameter.",
				"type": "string"
			},
			"value": {
				"description": "Value of the parameter."
			},
			"unit": {
				"description": "A CV element describing the unit of the parameter value.",
				"anyOf": [
					{
						"$ref": "#/definitions/cvParameter"
					},
					{
						"type": "array",
						"minItems": 1,
						"items": {
							"$ref": "#/definitions/cvParameter"
						}
					}
				]
			}
		},
		"required": ["cvRef", "accession", "name"]
	},
```

**Comment by bittremieux** [comment]
`cvParameter` is used as base element for a few other elements. However, it seems like only `qualityParameter` would actually have a `unit`. (**TODO**: Verify this.)

So I'd propose to remove `unit` from `cvParameter` and move it to `qualityParameter` to extend `cvParameter` instead.
That shouldn't invalidate any of our existing mzQC files I think.

**Comment by bittremieux** [comment]
@mwalzer What do you think about this now? Move `unit` to `qualityMetric` as this is the only `cvParameter` that actually has a unit, or just keep it as is?

That schema change wouldn't make a difference for the actual mzQC files.

**Comment by mwalzer** [comment]
Yep, I think a move into qualityMetric would be appropriate. Do you want to include that in #106 ?
