### ISSUE TITLE
[CV] units and more detailed description of how to compute metrics

### ISSUE THREAD

**Issue by cbielow** [HUPO-PSI/mzQC#72]
after going through some metrics in the current OBO, some descriptions are vague (at best) and/or ambiguous.
E.g. https://github.com/HUPO-PSI/mzQC/blob/master/cv/v0_1_0/qc-cv.obo#L194 says `Log ratio of ...`. Log to that base? There is no universal agreement IMHO. Writing `LogN` or `Log2` would be desirable and make QC values more comparable.

Also, most metrics could use a unit (e.g. for RT etc...). Is there a way to restrict (or even fix) the unit to be used?

Also, can we put restrictions on the values, e.g. fractions must be between 0-1. Reporting multiple fractions must sum to 1 etc...

The main idea/benefit of providing a tighter description is a) better interpretability of the data b) better comparability across tools which compute these metrics.

**Comment by bittremieux** [comment]
Whether or not to include units in the CV has been a topic of some discussion already. In the end we settled on having explicit units for the quality metrics in the mzQC files.

There should indeed be restrictions on some values. This is part of what the semantic validation of the official Python parser checks. So far we haven't made these restrictions explicit in the CV, but it might be relevant to consider that.

**Comment by bittremieux** [comment]
Overview of semantic validation in issue #50. Please add any checks that should still be included.

**Comment by julianu** [comment]
I agree, that many CVs need further description. It would be great, if the inventors of the metrics, or the persons who created them in their programs/workflows/pipelines could provide a better description.

The descriptions used by me so far where from some documents I found when I started to take over the CV or my own tries to interpret the CV.

The best way to get good descriptions for the items in the CV would be, if you could open an request-new-CV-entry-issue with the description etc.
(I know, I did not have much time in the last weeks, but should have some more to finish v1.0 now).

**Comment by bittremieux** [comment]
Probably the best way to get better descriptions is to ping the tool developers directly and explicitly mention the metrics that need to be improved. Otherwise I'm afraid not much will happen, as I doubt that many people will have seen this issue. :)

**Comment by julianu** [comment]
This will be handled by the "comment" information in the CV and the requirements for better descriptions in the future.
