### ISSUE TITLE
[CV] 'QC Metric type' category is confusing

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#73]
I fear the parent term (and CV term category) QC Metric type might be confusing. All subterms describe value types of metrics, not metric types.

**Comment by mwalzer** [comment]
I think this is two different things: metric types (like MS1, ID-free, environment ...) and metric value types (like single, tuple, matrix ...).

**Comment by mwalzer** [comment]
Here are some thoughts/discussion points on how things could be arranged. I also searched for existing definitions in other ontologies to reuse.
Value types: 
- Median : NCIT_C28007  
- Count : NCIT_C25463 
- Percentile : NCIT_C48919 
- Delta : NCIT_C54126 
- Sum : NCIT_C25697 
- Range : NCIT_C38013 ("The difference between the lowest and highest numerical values; the limits or scale of variation. [ NCI ]") 

- List: ???
- Matrix: ???
- Table: ??? 

Value family: 
- Computed value : NPO_1795 
- 'Raw extract': e.g. pump pressure??? 

Family: 
- MS1 
- MS2 
- Peptide 
- Feature 

Superfamily: 
- ID free 
- ID based 
- DIA 
- Chromatography 
- Collected  (-> Instrumentation ?)

**Comment by julianu** [comment]
Agree, let's rename the "QC Metric type" to "metric value type"

**Comment by julianu** [comment]
Renaming is added in #84.
If this is ok, please close issue.
