### ISSUE TITLE
I think the following basic cv terms are needed

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#76]
id-free:
* Number of MS1
* Number of MS2
* Number of chromatograms
* MZ aquisition range (MZ(m/z) boundaries)
* RT aquisition range (RT(s) boundaries)
* TIC (linked list of RT(s) and intensities)
* TIC outliers (list of outlier RT(s))
* MS2 injection times (linked list of precursor m/z and injection time(ms))
* List of S/N of MS2 spectra (linked list of precursor m/z and S/N)
* List of S/N of MS1 spectra (linked list of RT and S/N)

id:
* total number of PSM
* total number of identified peptides
* total number of identified protein
* total number of proteins uniquely identified (unique peptides)
* precursor / MC / delta ppm / TD / charge table (table of precursor m/z and delta ppm and missed cleavages and target/decoy distinction and charge)

* final ID/MS2 ratio

quant:
* Number of features (isotopic envelope)
* Number of features identified
* Number of features with id conflict

new relation:
* not-for-final-report (filter mzqc for volume reduction)

**Comment by mwalzer** [comment]
Linked list can be tables, too, I don't mind - depends how we decide on the metric type issue. #73

**Comment by mwalzer** [comment]
minor overlap with #71 
IMO those could be added there.

**Comment by mwalzer** [comment]
Metrics values SHOULD have 'has_units' designation for each value type and SHOULD have 'has_type' ? 
- What we could formally recommend:
- Metrics MUST descend from a superfamily of with 'is_a' 
- Can have other relations too, preferrably as 'part_of' 
- Metric MUST have 'develops_from' ('derives_from') if it is intended as reimplementation 
- Needed for a report can be described with cv term for a plot or report that 'has_part' of metric x, y, and z

**Comment by bittremieux** [comment]
Do you want to add those metrics as general metrics? I.e. not linked to a specific tool or implementation?

For the recommendations, we'll need to explicitly specify how MUST and SHOULD should be interpreted.

- What does `has_type` encode? The type of metric, i.e. single value, list, etc., to replace the `is_a` way this is specified at the moment? Or something else?
- How do you define a "report", or "needed" even?

I'd caution against adding too much complexity to the schema, which seems to be happening here.

**Comment by bittremieux** [comment]
These metrics are part of the PSI-MS CV in the mean time.
