### ISSUE TITLE
New batch of CV term requests, category: Identified signal

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#85]
Name:
Explained precursor intensity first quarter

Definition:
"Fraction of identified MS2 in the first quarter of precursor intensity."

Comment: Higher fractions of identified MS2 spectra indicate the efficiency of detection and sampling

Proposed value type:
- [ ] single value

Synonym: MS2-4A

---
Name:
Explained precursor intensity second quarter

Definition:
"Fraction of identified MS2 in the second quarter of precursor intensity."

Comment: Higher fractions of identified MS2 spectra indicate the efficiency of detection and sampling

Proposed value type:
- [ ] single value

Synonym: MS2-4B

---
Name:
Explained precursor intensity third quarter

Definition:
"Fraction of identified MS2 in the third quarter of precursor intensity."

Comment: Higher fractions of identified MS2 spectra indicate the efficiency of detection and sampling

Proposed value type:
- [ ] single value

Synonym: MS2-4C

---
Name:
Explained precursor intensity fourth quarter

Definition:
"Fraction of identified MS2 in the fourth quarter of precursor intensity."

Comment: Higher fractions of identified MS2 spectra indicate the efficiency of detection and sampling

Proposed value type:
- [ ] single value

Synonym: MS2-4D

---
Name:
Extent of identified precursor intensity

Definition:
"Ratio of 95th over 5th percentile of precursor intensity for identified peptides", 

Comment: Can be used to approximate the dynamic range of signal

Proposed value type:
- [ ] single value
{STATO:0000300}

Synonym: MS1-3A

---
Name:
"Precursor intensity range of identified MS2"

Definition:
"Minimum and maximum precursor intensity recorded and identified."

Comment: The intensity range of the identified precursors informs about the dynamic range of the acquisition. 

Proposed value type:
- [ ] n-tuple
{MS:1003085,MS:1003085}

---

Name:
Precursor intensity of identified MS2 Q1, Q2, Q3

Definition:
"From the distribution of precursor intensity of identified MS2, the quartiles Q1, Q2, Q3", 

Comment: The (un)identified precursor intensity distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Precursor intensity of unidentified MS2 Q1, Q2, Q3

Definition:
"From the distribution of precursor intensity of unidentified MS2, the quartiles Q1, Q2, Q3", 

Comment: The (un)identified precursor intensity distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Median S/N for MS1 spectra in RT range in which half of the peptides are identified

Definition:
"Median S/N for MS1 spectra in RT range in which half of the peptides are identified", 

Comment: Higher MS1 S/N may correlate with higher signal discrimination

Proposed value type:
- [ ] single value
{STATO:0000300}

Synonym: MS1-2A

---
Name:
Median of TIC values in the RT range in which the first half of peptides are identified

Definition:
"Median of TIC values in the RT range in which the first half of peptides are identified" 

Comment: Estimates the total absolute signal for peptides (may vary significantly between instruments)

Proposed value type:
- [ ] single value

Synonym: MS1-2B

---
Name:
Median S/N for MS1 spectra in the shortest RT range in which half of the peptides are identified

Definition:
"Median S/N for MS1 spectra in the shortest RT range in which half of the peptides are identified", 

Proposed value type:
- [ ] single value

---
Name:
Median of TIC values in the shortest RT range in which half of the peptides are identified

Definition:
"Median of TIC values in the shortest RT range in which half of the peptides are identified" 

Proposed value type:
- [ ] single value

---
Name:
Explained base peak intensity median

Definition:
"Median of the ratio of 'max survey scan intensity' over 'sampled precursor intensity' for all peptides identified" 

Comment: Gives insight into the amount of overall explained signal and whether the amount of signal could be increased by a better sampling strategy.

Proposed value type:
- [ ] single value
{STATO:0000574}

---
Name:
Explained base peak intensity median from least intense 50% base peaks

Definition:
"Ratios of 'max survey scan intensity' over sampled precursor intensity for the bottom half (by MS1 max) of MS2", 

Comment: Gives insight into the amount of explained signal and whether the sampling strategy is interfering with the sampling of low abundant peaks.

Proposed value type:
- [ ] single value

**Comment by julianu** [comment]
Does the Q1 in "Explained precursor intensity" mean the first quartile?

Could you please add comments (i.e. descriptions on how to interpret the values) for the metrics? And do this also for the other issues you added ;)

**Comment by julianu** [comment]
@mwalzer please add comments (explanations for interpretation)

**Comment by mwalzer** [comment]
@julianu added comments and unit suggestions (and some synoyms as they match previously proposed metrics from older publications)
