### ISSUE TITLE
New batch of CV term requests, category: Spectrum acquisition

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#86]
Name:
"Number of chromatograms"

Definition:
"Number of chromatograms"

Comment: A lower number of chromatograms acquired during one sample run compared to similar runs can indicate mismatched instrument settings or issues with the instrumentation.

Proposed value type:
- [ ] single value
{STATO:0000047}

---
Name:
"Number of MS1 spectra"

Definition:
"Number of MS1 spectra"

Comment: A lower number of MS1 spectra acquired during one sample run compared to similar runs can indicate mismatched instrument settings or issues with the instrumentation.

Proposed value type:
- [ ] single value
{STATO:0000047}

---
Name:
"Number of MS2 spectra"

Definition:
"Number of MS2 spectra"

Comment: A lower number of MS2 spectra acquired during one sample run compared to similar runs can indicate mismatched instrument settings or issues with the instrumentation or unusual low levels of ions collectable for MS/MS.

Proposed value type:
- [ ] single value
{STATO:0000047}

---
Name:
"MZ acquisition range"

Definition:
"Upper and lower limit of m/z values at which spectra are recorded."

Comment: Acquisition levels can be used as a criterion to assess the comparability of instrument settings between runs. 

Proposed value type:
- [ ] n-tuple
{MS:1000040,MS:1000040}

---
Name:
"RT acquisition range"

Definition:
"Upper and lower limit of time at which spectra are recorded."

Comment: Acquisition levels can be used as a criterion to assess the comparability of instrument settings between runs. 

Proposed value type:
- [ ] n-tuple
{UO:0000010,UO:0000010}

---
Name:
"Fastest frequency for MS level 1 collection"

Definition:
"Fastest frequency for MS level 1 collection"

Comment: Spectrum acquisition frequency can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{UO:0000106}

---

Name:
"Fastest frequency for MS level 2 collection"

Definition:
"Fastest frequency for MS level 2 collection"

Comment: Spectrum acquisition frequency can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{UO:0000106}

---

Name:
"Slowest frequency for MS level 1 collection"

Definition:
"Slowest frequency for MS level 1 collection"

Comment: Spectrum acquisition frequency can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{UO:0000106}

---

Name:
"Slowest frequency for MS level 2 collection"

Definition:
"Slowest frequency for MS level 2 collection"

Comment: Spectrum acquisition frequency can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{UO:0000106}

---
Name:
"Precursor intensity range"

Definition:
"Minimum and maximum precursor intensity recorded."

Comment: The intensity range of the precursors informs about the dynamic range of the acquisition. 

Proposed value type:
- [ ] n-tuple
{MS:1003085,MS:1003085}

**Comment by julianu** [comment]
Please add comments (i.e. descriptions on how to interpret the values) for the metrics.

**Comment by julianu** [comment]
@mwalzer please add comments (explanations for interpretation)

**Comment by mwalzer** [comment]
@julianu Updated with comments
I think acquisition frequency distribution might be more informative than fastest frequency only. Will add that, too.

**Comment by mwalzer** [comment]
I think we still need to figure out a neat way to make tuples and tables more computationally accessible. Like assigning unit types or in this case just types so that a parser can be automatically instructed what is in which position of the tuple. Like {STATO:0000401,STATO:0000237}

**Comment by mwalzer** [comment]
In favour of a better overview of things I moved the distribution bits to #87
