### ISSUE TITLE
New batch of CV term requests, category: Distributions of spectrum acquisition

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#87]
Name:
"MS1 frequency in RT quarters"

Definition:
"MS1 frequency in RT 1st quarter, 2nd quarter, 3rd quarter, 4th quarter"

Comment: Spectrum acquisition frequency can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] n-tuple
{UO:0000106,UO:0000106,UO:0000106,UO:0000106}

---
Name:
"MS2 frequency in RT quarters"

Definition:
"MS2 frequency in RT 1st quarter, 2nd quarter, 3rd quarter, 4th quarter"

Comment: Spectrum acquisition frequency can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] n-tuple
{UO:0000106,UO:0000106,UO:0000106,UO:0000106}

---
Name:
"MS1 trap time Q1, Q2, Q3"

Definition:
From the distribution of ion injection times (MS:1000927) for MS1, the quartiles Q1, Q2, Q3

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"MS1 trap time mean"

Definition:
From the distribution of ion injection times (MS:1000927) for MS1, the mean

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"MS1 trap time sigma"

Definition:
From the distribution of ion injection times (MS:1000927) for MS1, the sigma value

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"MS1 trap time outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of ion injection times (MS:1000927) for MS1, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
"MS2 trap time Q1, Q2, Q3"

Definition:
From the distribution of ion injection times (MS:1000927) for MS2, the quartiles Q1, Q2, Q3

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"MS2 trap time mean"

Definition:
From the distribution of ion injection times (MS:1000927) for MS2, the mean

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"MS2 trap time sigma"

Definition:
From the distribution of ion injection times (MS:1000927) for MS2, the sigma value

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"MS2 trap time outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of ion injection times (MS:1000927) for MS2, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: Injection time distribution can be used to gauge the suitability of used instrument settings for the sample content used.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
"Peak density distribution MS1 Q1, Q2, Q3"

Definition:
From the distribution of peak densities in MS1, the quartiles Q1, Q2, Q3

Comment: The distribution of peak densities in MS1 can provide insight into the presence of nuisance factors.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"Peak density distribution MS1 mean"

Definition:
From the distribution of peak densities in MS1, the mean

Comment: The distribution of peak densities in MS1 can provide insight into the presence of nuisance factors.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"Peak density distribution MS1 sigma"

Definition:
From the distribution of peak densities in MS1, the sigma value

Comment: The distribution of peak densities in MS1 can provide insight into the presence of nuisance factors.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"Peak density distribution MS1 outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of peak densities in MS1, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: The distribution of peak densities in MS1 can provide insight into the presence of nuisance factors.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
"Peak density distribution MS2 Q1, Q2, Q3"

Definition:
From the distribution of peak densities in MS2, the quartiles Q1, Q2, Q3

Comment: The distribution of peak densities in MS2 can provide insight into the instruments ion selction settings.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"Peak density distribution MS2 mean"

Definition:
From the distribution of peak densities in MS2, the mean

Comment: The distribution of peak densities in MS2 can provide insight into the instruments ion selction settings.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"Peak density distribution MS2 sigma"

Definition:
From the distribution of peak densities in MS2, the sigma value

Comment: The distribution of peak densities in MS2 can provide insight into the instruments ion selction settings.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"Peak density distribution MS2 outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of peak densities in MS2, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: The distribution of peak densities in MS2 can provide insight into the instruments ion selction settings.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
"Precursor intensity distribution Q1, Q2, Q3"

Definition:
From the distribution of precursor intensities, the quartiles Q1, Q2, Q3

Comment: The intensity distribution of the precursors informs about the dynamic range of the acquisition.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"Precursor intensity distribution mean"

Definition:
From the distribution of precursor intensities, the mean

Comment: The intensity distribution of the precursors informs about the dynamic range of the acquisition.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"Precursor intensity distribution sigma"

Definition:
From the distribution of precursor intensities, the sigma value

Comment: The intensity distribution of the precursors informs about the dynamic range of the acquisition.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"Precursor intensity distribution outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of precursor intensities, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: The intensity distribution of the precursors informs about the dynamic range of the acquisition.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

**Comment by julianu** [comment]
Please add comments (i.e. descriptions on how to interpret the values) for the metrics.

**Comment by julianu** [comment]
@mwalzer please add comments (explanations for interpretation)

**Comment by mwalzer** [comment]
@julianu  added comments and unit propositions, see #86 for thoughts on that one.
