### ISSUE TITLE
New batch of CV term requests, category: ESI stability

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#88]
Name:
"MS1 signal jump (10x) count"

Definition:
"The count of MS1 signal jump by a factor of ten or more (10x) between two subsequent scans"

Comment: An unusual high count of signal jumps or falls (QC:0000x) can indicate ESI stability issues.

Proposed value type:
- [ ] single value

Synonym: IS-1A

---
Name:
"MS1 signal fall (10x) count"

Definition:
"The count of MS1 signal decline by a factor of ten or more (10x) between two subsequent scans"

Comment: An unusual high count of signal jumps (QC:0000x) or falls can indicate ESI stability issues.

Proposed value type:
- [ ] single value

Synonym: IS-1B

**Comment by julianu** [comment]
Please add comments (i.e. descriptions on how to interpret the values) for the metrics.

**Comment by julianu** [comment]
@mwalzer please add comments (explanations for interpretation)

**Comment by mwalzer** [comment]
@julianu proposal updated with comments and synonyms.

**Comment by mwalzer** [comment]
Actually, I think a consecutive stretch of low signal would be more robust to ESI instability detection. The detection with counts here is only possible relative for a group of runs with the same gradient settings and sample contents.
