### ISSUE TITLE
New batch of CV term requests, category: Identifications

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#89]
Name:
Charge 1+ to charge 2+ peptides

Definition:
Ratio of 1+ peptide count  over 2+ peptide count  in identified spectra

Proposed value type:
- [ ] single value
---
Name:
Charge 3+ to charge 2+ peptides

Definition:
Ratio of 3+ peptide count over 2+ peptide count in identified spectra

Proposed value type:
- [ ] single value
---
Name:
Charge 4+ to charge 2+ peptides

Definition:
Ratio of 4+ peptide count over 2+ peptide count in identified spectra

Proposed value type:
- [ ] single value
---
Name:
Mean charge in identified spectra

Definition:
Mean charge in identified spectra

Proposed value type:
- [ ] single value
---
Name:
Median charge in identified spectra

Definition:
Median charge in identified spectra

Proposed value type:
- [ ] single value
---
Name:
Charge 1+ to charge 2+ spectra

Definition:
Ratio of 1+ peptide count  over 2+ peptide count  in all MS2

Proposed value type:
- [ ] single value
---
Name:
Charge 3+ to charge 2+ spectra

Definition:
Ratio of 3+ peptide count over 2+ peptide count  in all MS2

Proposed value type:
- [ ] single value
---
Name:
Charge 4+ to charge 2+ spectra

Definition:
Ratio of 4+ peptide count over 2+ peptide count  in all MS2

Proposed value type:
- [ ] single value
---
Name:
Mean charge in all MS2

Definition:
Mean charge in all MS2

Proposed value type:
- [ ] single value
---
Name:
Median charge in all MS2

Definition:
Median charge in all MS2

Proposed value type:
- [ ] single value
---
Name:
Number of missed cleavages

Definition:
Number of missed cleavages

Proposed value type:
- [ ] single value
---
Name:
Total number of protein evidences

Definition:
Total number of protein evidences

Proposed value type:
- [ ] single value
---
Name:
Number of identified proteins

Definition:
Number of identified proteins

Proposed value type:
- [ ] single value
---
Name:
Total number of PSM

Definition:
Total number of PSM

Proposed value type:
- [ ] single value
---
Name:
Number of identified peptides

Definition:
Number of identified peptides

Proposed value type:
- [ ] single value
---
Name:
Number of identified spectra

Definition:
Number of  identified spectra

Proposed value type:
- [ ] single value
---
Name:
ID ratio

Definition:
The ratio of identified and recorded spectra.

Proposed value type:
- [ ] single value
---

**Comment by mwalzer** [comment]
I guess it might make sense to keep an eye on the 'mc' in all PSM ranks. How could we encode that?

**Comment by julianu** [comment]
Please add comments (i.e. descriptions on how to interpret the values) for the metrics.

**Comment by julianu** [comment]
@mwalzer please add comments (explanations for interpretation)
