### ISSUE TITLE
New batch of CV term requests, category: Identifications (distributions)

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#90]
Name:
Precursor errors (abs) Q1, Q2, Q3

Definition:
From the distribution of Precursor errors (abs), the quartiles Q1, Q2, Q3 value

Comment: The absolute precursor error distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Precursor errors (abs) mean

Comment: The absolute precursor error distribution can aid the interpretation of overall identification success.

Definition:
From the distribution of Precursor errors (abs), the mean

Proposed value type:
- [ ] single value
{STATO:0000401}

Synonym: MS1-5B

---
Name:
Precursor errors (abs) sigma

Definition:
From the distribution of Precursor errors (abs), the sigma value

Comment: The absolute precursor error distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Precursor errors (abs) outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of Precursor errors (abs), the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: The absolute precursor error distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
Precursor errors (ppm) Q1, Q2, Q3

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Definition:
From the distribution of Precursor errors (ppm), the quartiles Q1, Q2, Q3 value

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Precursor errors (ppm) mean

Definition:
From the distribution of Precursor errors (ppm), the mean 

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
Precursor errors (ppm) sigma

Definition:
From the distribution of Precursor errors (ppm), the sigma value

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Precursor errors (ppm) outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of Precursor errors (ppm), the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---

Name:
Precursor errors (abs) median

Definition:
From the distribution of Precursor errors (abs), the median 

Comment: The precursor error distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] single value
{STATO:0000401}

Synonym: MS1-5A

---
Name:
Precursor errors (ppm) median

Definition:
From the distribution of Precursor errors (ppm), the median 

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] single value
{STATO:0000401}

Synonym: MS1-5C

---
Name:
Precursor errors (ppm) IQR

Definition:
From the distribution of Precursor errors (ppm), the IQR

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] single value
{STATO:0000401}

Synonym: MS1-5D

---
Name:
Identification score Q1, Q2, Q3

Definition:
From the distribution of Identification score, the Q1, Q2, Q3 value

Comment: The precursor error in ppm distribution can aid the interpretation of overall identification success.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Identification score mean

Definition:
From the distribution of Identification score, the mean value

Comment: The identification score distribution can help improve scoring function tuning, aid the interpretation of overall identification success, and integration with downstream processing such as percolator.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
Identification score sigma

Definition:
From the distribution of Identification score, the sigma value

Comment: The identification score distribution can help improve scoring function tuning, aid the interpretation of overall identification success, and integration with downstream processing such as percolator.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Identification score outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of Identification score, the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: The identification score distribution can help improve scoring function tuning, aid the interpretation of overall identification success, and integration with downstream processing such as percolator.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
Missed cleavages in identified peptides Q1, Q2, Q3

Definition:
From the distribution of missed cleavages in identified peptides the quartiles Q1, Q2, Q3 value

Comment: The missed cleavage distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Missed cleavage mean

Definition:
From the distribution of missed cleavages in identified peptides the mean

Comment: The missed cleavage distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] single value
{STATO:0000401}

Synonym: MS1-5B

---
Name:
Missed cleavage sigma

Definition:
From the distribution of missed cleavages in identified peptides the sigma value

Comment: The missed cleavage distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Missed cleavage outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of missed cleavages in identified peptides, the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: The missed cleavage distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
Identified peptide lengths Q1, Q2, Q3

Definition:
From the distribution of identified peptide lengths the quartiles Q1, Q2, Q3 value

Comment: The identified peptide lengths distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Missed cleavage mean

Definition:
From the distribution of identified peptide lengths the mean

Comment: The identified peptide lengths distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] single value
{STATO:0000401}

Synonym: MS1-5B

---
Name:
Missed cleavage sigma

Definition:
From the distribution of identified peptide lengths the sigma value

Comment: The identified peptide lengths distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Missed cleavage outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of identified peptide lengths, the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: The identified peptide lengths distribution can aid the interpretation of digestion efficacy.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
Signal-to-noise ratio in MS1 Q1, Q2, Q3

Definition:
From the distribution of signal-to-noise ratio in MS1, the quartiles Q1, Q2, Q3 value

Comment: The Signal-to-noise ratio in MS1 distribution can provide insight to the presence of nuisance factors.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Signal-to-noise ratio in MS1 mean

Comment: The signal-to-noise ratio in MS1 distribution can provide insight into the presence of nuisance factors.

Definition:
From the distribution of signal-to-noise ratio in MS1, the mean

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
Signal-to-noise ratio in MS1 sigma

Definition:
From the distribution of signal-to-noise ratio in MS1, the sigma value

Comment: The Signal-to-noise ratio in MS1 distribution can provide insight into the presence of nuisance factors.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Signal-to-noise ratio in MS1 outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of signal-to-noise ratio in MS1, the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: The Signal-to-noise ratio in MS1 distribution can provide insight into the presence of nuisance factors.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
Signal-to-noise ratio in MS2 Q1, Q2, Q3

Definition:
From the distribution of signal-to-noise ratio in MS2, the quartiles Q1, Q2, Q3 value

Comment: A high signal-to-noise ratio in MS2 distribution can explain a high rate of unidentified spectra.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
Signal-to-noise ratio in MS2 mean

Definition:
From the distribution of signal-to-noise ratio in MS2, the mean

Comment: A high signal-to-noise ratio in MS2 distribution can explain a high rate of unidentified spectra.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
Signal-to-noise ratio in MS1 sigma

Definition:
From the distribution of signal-to-noise ratio in MS2, the sigma value

Comment: A high signal-to-noise ratio in MS2 distribution can explain a high rate of unidentified spectra.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
Signal-to-noise ratio in MS2 outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)

Definition:
From the distribution of signal-to-noise ratio in MS2, the list of outliers below of Q1-1.5IQR and above Q3+1.5IQR

Comment: A high signal-to-noise ratio in MS2 distribution can explain a high rate of unidentified spectra.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
"Identified precursor intensity distribution Q1, Q2, Q3"

Definition:
From the distribution of identified precursor intensities, the quartiles Q1, Q2, Q3

Comment: The intensity distribution of the identified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"Identified precursor intensity distribution mean"

Definition:
From the distribution of identified precursor intensities, the mean

Comment: The intensity distribution of the identified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"Identified precursor intensity distribution sigma"

Definition:
From the distribution of identified precursor intensities, the sigma value

Comment: The intensity distribution of the identified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"Identified precursor intensity distribution outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of identified precursor intensities, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: The intensity distribution of the identified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

---
Name:
"Unidentified precursor intensity distribution Q1, Q2, Q3"

Definition:
From the distribution of unidentified precursor intensities, the quartiles Q1, Q2, Q3

Comment: The intensity distribution of the unidentified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] n-tuple
{STATO:0000167, STATO:0000574, STATO:0000170}

---
Name:
"Unidentified precursor intensity distribution mean"

Definition:
From the distribution of unidentified precursor intensities, the mean

Comment: The intensity distribution of the unidentified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] single value
{STATO:0000401}

---
Name:
"Unidentified precursor intensity distribution sigma"

Definition:
From the distribution of unidentified precursor intensities, the sigma value

Comment: The intensity distribution of the unidentified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] single value
{STATO:0000237}

---
Name:
"Unidentified precursor intensity distribution outliers (<Q1-1.5*IQR, >Q3+1.5*IQR)"

Definition:
From the distribution of unidentified precursor intensities, the list of outliers below of Q1-1.5*IQR and above Q3+1.5*IQR

Comment: The intensity distribution of the unidentified precursors informs about the dynamic range of the acquisition in relation to identifiability.

Proposed value type:
- [ ] n-tuple
{'NCIT:C75330':[...], 'NCIT:C75329':[...]}
{'below':[...], 'above':[...]}

**Comment by mwalzer** [comment]
How  could we encode the "type" of score used in the last distribution set?

**Comment by julianu** [comment]
Please add comments (i.e. descriptions on how to interpret the values) for the metrics.

**Comment by julianu** [comment]
@mwalzer please add comments (explanations for interpretation)
