### ISSUE TITLE
[CV request] Total ion chromatogram separately for all MSn

### ISSUE THREAD

**Issue by weiclav** [HUPO-PSI/mzQC#92]
Hi,

I would like to see total ion chromatograms separately for individual scan level, e.g. MS1 and MS2. I.e. similar to QC:0000022, just separately for individual levels. Not sure if it should be connected also with individual spectrum TIC from the given level or MS:1000285 can cover that...

How to interpret the metric value:
It can give some insight into several potential issues when plotted like MS1 TIC fluctuations (spray issue, bubbles coming out from the LC system, etc.), evaluation of the absolute MS2 TIC values in combination with MS1 TIC etc.

Proposed value type:
- [ ] table

Identifications needed (if appropriate):
- [ ] ID free

Best,
David

**Comment by julianu** [comment]
Hallo David,

I would add the terms for MS1 and MS2 like these, does this look ok? Especially the comment/explanation for interpretation for the MS2 TIC might need some more investigation, not sure:

```
[Term]
id: QC:4XXXXXX
name: MS1 Total ion current chromatogram
def: "The total ion current chromatogram of MS1 measurements. The first list contains the retention time values in second, the second list the corresponding abundances." [PSI:QC]
comment: The metric gives some insight into several potential issues when plotted like MS1 TIC fluctuations (spray issue, bubbles coming out from the LC system, etc.), evaluation of the absolute MS2 TIC values in combination with MS1 TIC etc.
xref: value-type:xsd\:int "The allowed value-type for this CV term."
is_a: QC:4000005 ! corresponding lists
is_a: QC:4000010 ! ID free
is_a: QC:4000022 ! chromatogram metric
is_a: QC:4000023 ! MS1 metric
relationship: has_relation QC:4000013 ! QC metric relation: one run
relationship: has_relation QC:4000067 ! Total ion current chromatogram

[Term]
id: QC:4XXXXXX
name: MS2 Total ion current chromatogram
def: "The total ion current chromatogram of MS2 measurements. The first list contains the retention time values in second, the second list the corresponding abundances." [PSI:QC]
comment: The metric gives some insight into several potential issues when plotted like MS2 TIC fluctuations (spray issue, bubbles coming out from the LC system, etc.), evaluation of the absolute MS2 TIC values in combination with MS1 TIC etc.
xref: value-type:xsd\:int "The allowed value-type for this CV term."
is_a: QC:4000005 ! corresponding lists
is_a: QC:4000010 ! ID free
is_a: QC:4000022 ! chromatogram metric
is_a: QC:4000024 ! MS2 metric
relationship: has_relation QC:4000013 ! QC metric relation: one run
relationship: has_relation QC:4000067 ! Total ion current chromatogram
```

**Comment by weiclav** [comment]
Hi Julian,

thanks for the initial setup! Yes, Comments may need some polishing also from others if possible - I am not using the terms heavily so I may be missing "the bigger picture" here. Anyway, can you recommend me some good examples so I can rephrase the initial ones?

Thanks!
David

**Comment by julianu** [comment]
Hej David,

As we are still in the construction phase of the first big release and the comments are just introduced, there are not many yet.
But these should just help someone, who has no idea how to interpret the values of the metric. But TICs are relatively clear what they are and the interpretation, at least as far as I know, also depends a bit on your daily work with the machine.
Just wanted to double check, whether the explanation is ok. If you think, they are fine, I will merge them. And if we need to improve the explanation, we still can do so in the future.

**Comment by weiclav** [comment]
Thanks for additional info, will check it once more and get back to you within a few days.

**Comment by weiclav** [comment]
Hi Julian,

sorry for later response. Here is what I think might explain the metrics a bit.

name: MS1 Total ion current chromatogram
comment: The metric enables to check visually e.g. MS1 TIC stability along the retention time and its absolute value compared to MS2 total ion chromatogram or other analyses MS1 TICs. TIC drops caused by e.g. spray stability issues or bubbles presence can be detected here.

name: MS2 Total ion current chromatogram
comment: The metric enables to check visually e.g. MS2 TIC absolute value compared to MS1 total ion chromatogram or other analyses MS2 TICs.

**Comment by julianu** [comment]
The terms will be added as soon as #84 is merged/accepted.

**Comment by julianu** [comment]
Added in #95
