### ISSUE TITLE
Update readme.md in the CV folder ..

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzQC#94]
.. to reflect how the new CV term request workflow works.

**Comment by julianu** [comment]
Is also in the PR #84 now
Is there a way to make a new PR from my branch for these smaller changes?

**Comment by bittremieux** [comment]
It should be possible to use a specific branch other than `master` as starting point for a PR.

**Comment by julianu** [comment]
This PR got accidentally accepted...
Is the readme ok like this?
